### ISSUE TITLE
Make `screens/plant_show` more compact

### ISSUE THREAD

**Issue by katrinleinweber** [abertschi/water-me#16]
Hello & thanks for this neat helper :-)

I'm noticing a small… Large… _Size_ issue on a Fairphone 3+ screen with default font-size configured in /e/ OS: the `WATER NOW` button is only visible without scrolling when the plant name has 7 letters or less.

Any longer name creates a linebreak, which in combination with the 2-line `water every …` and `watered …` lines push the button down. The `fontSize`s and `SizedBox(height`s are surprisingly large by default, so even reducing the OS font size provides shifts the display problem by only 1 character.

I know one can swipe on the main screen. However, if one is on the plant's own screen for any reason, it's still a bit strange to have to scroll down for the main action.

Therefore: Could the screen please be compacted a little bit? For example as in [my `compact-plant-show-screen` branch](https://github.com/abertschi/water-me/compare/master...katrinleinweber:water-me:compact-plant-show-screen?expand=1#diff-887812deda2a6d78a95e242b1cd6f44f04676a282d710eaa97d1baef0a74d020)? Please feel free to pull that, if you find it useful.

---

Alternative ideas:

a) Could the icon on the main screen be turned into a button, so that going into `screens/plant_show` is only necessary for checking the stats?

b) The water droplet icon could be moved to the same line as the plant name.

c) The `WATER NOW` button could be moved above all other text on `screens/plant_show`.

**Comment by abertschi** [comment]
Can you visualize the issue with a screenshot?
Regarding alternative idea a: 
https://github.com/abertschi/water-me/issues/13#issuecomment-1235269113

**Comment by katrinleinweber** [comment]
Sure :-) 

<details><summary>With small font size:</summary><img src="https://user-images.githubusercontent.com/9948149/195515923-bd4ba520-c9b7-458e-bc8b-11c9b2bca919.png"></details>

<details><summary>With default font size:</summary><img src="https://user-images.githubusercontent.com/9948149/195516212-84cadd8e-c460-4353-8e47-818fcf768a6d.png"></details>

**Comment by abertschi** [comment]
I see, thanks! :). not ideal. the current layout was designed with a device in mind which had more screen real estate that yours. The underlying problem is that the spacing is not dependent on the screen height but rather fix values. 

I agree the layout could be made more compact.
- Either by redesigning it,
- or by making the spacing dependent on some unit, e.g. something like `MediaQuery.of(context).size.height`, but unsure how this scales to landscape mode.

**Comment by katrinleinweber** [comment]
I drafted a few resizings in https://github.com/abertschi/water-me/pull/22. Not based on a real understanding of front-end development, though.
