### ISSUE TITLE
Getting this error

### ISSUE THREAD

**Issue by fahmidul** [abertschi/water-me#26]
![t1](https://user-images.githubusercontent.com/22258130/232867823-d499b407-103e-492f-8eed-bac4c7d16e11.png)

**Comment by abertschi** [comment]
can you elaborate? what version of the app are you using? and when does it happen? did you try to clear the app cache and reset the app?

**Comment by abertschi** [comment]
thanks for reaching out, will be fixed in next version

**Comment by abertschi** [comment]
Released in v1.0.8. will take a few days until available in fdroid store

**Comment by fahmidul** [comment]
Sorry for the late response and thanks a lot for your update.

**Comment by abertschi** [comment]
sure thing, let me know if there are some other issues :+1:

**Comment by fahmidul** [comment]
Sure 🙂

**Comment by abertschi** [comment]
Upon each new commit, the github runner will build a new apk, the latest build is available here: https://github.com/abertschi/water-me/actions/runs/4768649357 

(github zips the apk upon download, so needs unzip first)

cheers

**Comment by fahmidul** [comment]
Yes I have run zip file of latest codebase its working fine. 
Thanks for your concern.
