### ISSUE TITLE
black screen on start without existing user data

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [abertschi/water-me#27]
After starting the app version 1.0.7, I only see a black screen.

Tested device:
Samsung S21 5G
Android 13

**Comment by abertschi** [comment]
did you try to clean the cache? the data is lost if you clean the cache, however.

**Comment by abertschi** [comment]
Did previous versions work?

**Comment by mondlicht-und-sterne** [comment]
> Did previous versions work?

1.0.2 works

![Screenshot_20230419_225753-01](https://user-images.githubusercontent.com/61406324/233198945-570f0be0-eecb-4b28-a1c5-254ae651bc5f.jpeg)

**Comment by abertschi** [comment]
Ok, to further pin point the issue, what about version 5 and 6?
You find them on the fdroid site, I stopped bundling the apk after version 2.

https://f-droid.org/packages/ch.abertschi.waterme.water_me/

**Comment by abertschi** [comment]
Ok, so we need the debug output to troubleshoot.
Are you familiar with logcat? Can you post the app trace in logcat?

**Comment by 7eter** [comment]
i experienced the same problem only after **fresh install** of 1.0.7.
When upgrading from 1.0.6 to 1.0.7 everything works fine! (The version 1.0.6 must be opened at least once for this to work)

**Comment by abertschi** [comment]
Thanks for shouting out, yes there is a serialization issue in case no data is present. Will create a new version

**Comment by abertschi** [comment]
#26

**Comment by abertschi** [comment]
Released in v1.0.8

**Comment by mondlicht-und-sterne** [comment]
After update to the latest version fixes the error. The app isz normal usable. Thank you.

**Comment by abertschi** [comment]
version available in fdroid
