### ISSUE TITLE
Design a nice logo

### ISSUE THREAD

**Issue by abertschi** [abertschi/water-me#4]

**Comment by inigochoa** [comment]
Hey! Love the app and love your work! I wish I had the knowledge to do the things you do.

About the logo, I use Arcticons as my main icon-pack. The designer sometimes offers help with logo designs. You might consider getting in touch with him if you want to change it and need ideas. It would also be great if you could include the logo inside the articons.

**Comment by abertschi** [comment]
Thanks for reaching out and using the app. Designing a logo has low priority in my fun-queue, maybe you want to help me out and try to get in touch with someone if you know people. Otherwise we will just leave this open for someone else to take the lead.

**Comment by 7eter** [comment]
i think the water-droplet used inside the app is quiet nice! 
![WaterMe_350](https://user-images.githubusercontent.com/15588476/233500239-d7efa54d-0c85-46d2-98b1-5cd89f197963.png)

**Comment by abertschi** [comment]
This is awesome! Can you upload the svg file?

**Comment by 7eter** [comment]
![WaterMe](https://user-images.githubusercontent.com/15588476/233588515-f9f10e26-cce5-4c7d-9fef-6ede06fdcf76.svg)
sure thing! 😉
