### ISSUE TITLE
[feature request] backup / data export

### ISSUE THREAD

**Issue by citizenserious** [abertschi/water-me#8]
Would be awesome if there would be an option to safe the database. This would give the option to import it later or to transfer the database onto another device, especially if you have a lot of plants that would be useful (:
Thank you for this create app.

**Comment by abertschi** [comment]
thanks for filing an issue and using the app. agree, sounds like a reasonable feature :+1:

**Comment by abertschi** [comment]
Released in version 7.
https://github.com/abertschi/water-me/blob/master/qna.md
